#!/usr/bin/env python3
"""Turn Jira bugs into ready-to-post BugTrail comments.

Deliberately does no network I/O. Jira reads and writes go through the approved
Atlassian integration, driven by the agent; this script owns only the part that
must be deterministic and reviewable - deciding what the comment should say.

    in : [{key, summary, description, created, commentId?}]
    out: [{key, commentId, commentBody}]

Anything without a confident suspect is dropped rather than commented on. A bot
that posts "I found nothing" on every ticket gets muted within a week.

Usage:
    python3 tools/bugtrail/jira_bot.py --repo ../wbd-beam-swift \
        --issues .local/new-bugs.json --out .local/comments.json
"""

from __future__ import annotations

import argparse
import json
import re
import subprocess
import sys
from pathlib import Path

HERE = Path(__file__).resolve().parent
sys.path.insert(0, str(HERE))

from cli import analyse, jira_source, load_config  # noqa: E402
from ranking import confidence_label  # noqa: E402
from repo import ensure_repo, resolve_ref  # noqa: E402

BOT_NAME = "Bug Slayers Bot"

# Plain token rather than an HTML comment: Jira wiki markup has no comment
# syntax, and the marker has to survive a round trip so re-runs can find and
# update their own previous comment instead of posting a second one.
MARKER = "bug-slayers:v1"

# Tickets answered before the rename carry the old token. Detection has to go on
# accepting it: the marker is how a re-run recognises its own work, so dropping
# it would make every previously answered ticket look untouched and earn a
# second comment.
LEGACY_MARKERS = ("bugtrail:v1",)
KNOWN_MARKERS = (MARKER,) + LEGACY_MARKERS

DISCLAIMER = (
    "_Generated by %s from git history. These are likely related changes, "
    "not a verdict - please review before acting._" % BOT_NAME
)


# A second marker on the "could not attribute" note. Without it, silence and a
# real answer are indistinguishable on a re-run, and the ticket would be stuck
# with the note for good: the code the reporter had not yet pushed lands, the
# analysis would now succeed, and the agent skips because it sees its own
# marker and assumes the work is done.
INCONCLUSIVE_MARKER = "inconclusive"


def bot_banner() -> list:
    """A coloured header identifying the author, because Jira's will not.

    Jira attributes a comment to whoever's token authenticated it, and ours is a
    personal one - so every comment reads as written by a colleague, which is
    the single distinction a triage suggestion most needs to make. The service
    account that fixes it properly is an access request away, and until it
    lands this is the part of the byline we control: a banner the eye reaches
    before the grey name above it.

    Deliberately no nested macros. A {quote} or heading inside a panel renders
    inconsistently depending on which editor the site is using, and a comment
    that shows raw markup is worse than a plain one.
    """
    return [
        "{panel:bgColor=#deebff}",
        "🤖 *%s* — automated triage, not a human judgement" % BOT_NAME,
        "{panel}",
        "",
    ]


def is_our_comment(body: str) -> bool:
    return any(m in (body or "") for m in KNOWN_MARKERS)


def is_inconclusive(body: str) -> bool:
    return is_our_comment(body) and INCONCLUSIVE_MARKER in (body or "")


def render_inconclusive(bug_key: str, reason: str, detail: str = "") -> str:
    """Say nothing was found, and why, rather than staying silent.

    Silence is ambiguous - the reporter cannot tell a broken agent from one that
    looked and found nothing. Naming the reason also makes the note actionable,
    because every reason here has a fix the reporter can apply.
    """
    lines = bot_banner() + [
        "h3. No suspect found",
        "",
        "*Reason:* %s" % reason,
    ]
    if detail:
        lines += ["", detail]
    lines += [
        "",
        "This is not a verdict that no change caused it - only that nothing in "
        "the repository history matched confidently enough to name someone. "
        "Attributing a defect to the wrong author is worse than saying nothing.",
        "",
        "_Generated by %s. It will replace this note automatically if a later "
        "run can attribute the change._" % BOT_NAME,
        "",
        "_%s %s_" % (MARKER, INCONCLUSIVE_MARKER),
    ]
    return "\n".join(lines)


def github_base(repo: str) -> str:
    url = subprocess.run(
        ["git", "-C", repo, "remote", "get-url", "origin"],
        capture_output=True, text=True,
    ).stdout.strip()
    m = re.search(r"github\.com[:/](.+?)(?:\.git)?$", url)
    return "https://github.com/%s" % m.group(1) if m else ""


def render_comment(result, ranked, repo: str, base: str) -> str:
    """Jira wiki markup, which the v2 comment API accepts directly."""
    bug = result.bug
    top = result.suspects[0]
    c = top.candidate
    lines = bot_banner() + ["h3. Suspect change", ""]

    if c.pr_number and base:
        pr = "[PR #%d|%s/pull/%d]" % (c.pr_number, base, c.pr_number)
    elif c.pr_number:
        pr = "PR #%s" % c.pr_number
    else:
        pr = "commit {{%s}}" % c.commit.sha[:10]

    lines.append(
        "*Most likely:* %s — %s, %s"
        % (pr, c.commit.author_name, c.commit.authored_at.date().isoformat())
    )
    lines.append("{quote}%s{quote}" % c.commit.subject)
    lines.append("*Why:*")
    for reason in top.reasons:
        lines.append("* %s" % reason)
    lines.append("")

    lines.append("*Starting point:* {{%s}}" % bug.seed_file)
    if ranked and ranked[0].reasons:
        lines.append("_Why this file: %s._" % ranked[0].reasons[0].replace("`", ""))
    lines.append("")

    if len(result.suspects) > 1:
        lines.append("*Other candidates:*")
        for s in result.suspects[1:3]:
            sc = s.candidate
            label = "PR #%s" % sc.pr_number if sc.pr_number else "{{%s}}" % sc.commit.sha[:10]
            lines.append(
                "* %s — %s, %s"
                % (label, sc.commit.author_name, sc.commit.authored_at.date().isoformat())
            )
        lines.append("")

    lines.append(
        "*Confidence:* %s (%.2f)"
        % (confidence_label(result.confidence), result.confidence)
    )
    lines.append("")
    lines.append(DISCLAIMER)
    lines.append("")
    lines.append("_%s_" % MARKER)
    return "\n".join(lines)


def main() -> int:
    ap = argparse.ArgumentParser()
    ap.add_argument(
        "--repo",
        help="local path, clone URL, or owner/name. Defaults to config 'repo'",
    )
    ap.add_argument(
        "--no-fetch",
        action="store_true",
        help="skip refreshing the checkout (offline reruns only)",
    )
    ap.add_argument("--ref", help="revision to analyse; defaults to origin's default branch")
    ap.add_argument("--issues", required=True)
    ap.add_argument("--out", required=True)
    ap.add_argument("--config", default=str(HERE / "config.json"))
    ap.add_argument("--history-limit", type=int, default=60)
    ap.add_argument(
        "--min-confidence", type=float, default=0.25,
        help="below this, stay quiet rather than guess out loud",
    )
    args = ap.parse_args()

    config = load_config(Path(args.config))
    config["historyLimit"] = args.history_limit

    # Posting to a real ticket off a stale clone is worse than posting nothing,
    # so the refresh is on by default here.
    args.repo = ensure_repo(
        args.repo or config.get("repo") or "",
        fetch_local=not args.no_fetch,
    )
    config["ref"] = resolve_ref(args.repo, args.ref)
    print("[repo] analysing %s at %s" % (args.repo, config["ref"]))
    base = github_base(args.repo)

    issues = json.loads(Path(args.issues).read_text())
    scratch = Path(args.out).parent / "_issue.json"
    prepared, skipped = [], []

    for issue in issues:
        key = issue["key"]
        scratch.write_text(json.dumps(issue))
        bug, ranked = jira_source(scratch, args.repo, config)
        if bug is None:
            skipped.append((key, "no candidate file located"))
            continue

        result = analyse(args.repo, bug, config)
        if not result.suspects or result.confidence < args.min_confidence:
            skipped.append((key, "confidence %.2f below threshold" % result.confidence))
            continue

        prepared.append({
            "key": key,
            "commentId": issue.get("commentId"),
            "commentBody": render_comment(result, ranked, args.repo, base),
            "seedFile": bug.seed_file,
            "confidence": round(result.confidence, 3),
        })

    if scratch.exists():
        scratch.unlink()

    Path(args.out).write_text(json.dumps(prepared, indent=2))

    print("prepared %d comment(s); skipped %d" % (len(prepared), len(skipped)))
    for key, why in skipped:
        print("  skip %-14s %s" % (key, why))
    for p in prepared:
        print("  post %-14s seed=%s conf=%.2f"
              % (p["key"], p["seedFile"].rsplit("/", 1)[-1], p["confidence"]))
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
