#!/usr/bin/env python3
"""Turn Jira bugs into ready-to-post BugTrail comments.

Deliberately does no network I/O. Jira reads and writes go through the approved
Atlassian integration, driven by the agent; this script owns only the part that
must be deterministic and reviewable - deciding what the comment should say.

    in : [{key, summary, description, created, commentId?}]
    out: [{key, commentId, commentBody}]

Anything without a confident suspect is dropped rather than commented on. A bot
that posts "I found nothing" on every ticket gets muted within a week.

Usage:
    python3 tools/bugtrail/jira_bot.py --repo ../wbd-beam-swift \
        --issues .local/new-bugs.json --out .local/comments.json
"""

from __future__ import annotations

import argparse
import json
import re
import subprocess
import sys
from pathlib import Path

HERE = Path(__file__).resolve().parent
sys.path.insert(0, str(HERE))

from cli import analyse, jira_source, load_config  # noqa: E402
from ranking import confidence_label  # noqa: E402

MARKER = "<!-- bugtrail:v1 -->"
DISCLAIMER = (
    "_Generated by BugTrail from git history. These are likely related changes, "
    "not a verdict - please review before acting._"
)


def github_base(repo: str) -> str:
    url = subprocess.run(
        ["git", "-C", repo, "remote", "get-url", "origin"],
        capture_output=True, text=True,
    ).stdout.strip()
    m = re.search(r"github\.com[:/](.+?)(?:\.git)?$", url)
    return "https://github.com/%s" % m.group(1) if m else ""


def render_comment(result, ranked, repo: str, base: str) -> str:
    bug = result.bug
    top = result.suspects[0]
    c = top.candidate
    lines = [MARKER, "*BugTrail — suspect change*", ""]

    pr = (
        "[PR #%d](%s/pull/%d)" % (c.pr_number, base, c.pr_number)
        if c.pr_number and base
        else ("PR #%s" % c.pr_number if c.pr_number else "commit %s" % c.commit.sha[:10])
    )
    lines.append(
        "*Most likely:* %s — %s, %s"
        % (pr, c.commit.author_name, c.commit.authored_at.date().isoformat())
    )
    lines.append("> %s" % c.commit.subject)
    lines.append("")
    lines.append("*Why:*")
    for reason in top.reasons:
        lines.append("* %s" % reason)
    lines.append("")

    lines.append(
        "*Starting point:* `%s`" % bug.seed_file
    )
    if ranked and ranked[0].reasons:
        lines.append("_Why this file: %s._" % ranked[0].reasons[0])
    lines.append("")

    if len(result.suspects) > 1:
        lines.append("*Other candidates:*")
        for s in result.suspects[1:3]:
            sc = s.candidate
            label = "PR #%s" % sc.pr_number if sc.pr_number else sc.commit.sha[:10]
            lines.append(
                "* %s — %s, %s"
                % (label, sc.commit.author_name, sc.commit.authored_at.date().isoformat())
            )
        lines.append("")

    lines.append(
        "*Confidence:* %s (%.2f)"
        % (confidence_label(result.confidence), result.confidence)
    )
    lines.append("")
    lines.append(DISCLAIMER)
    return "\n".join(lines)


def main() -> int:
    ap = argparse.ArgumentParser()
    ap.add_argument("--repo", required=True)
    ap.add_argument("--issues", required=True)
    ap.add_argument("--out", required=True)
    ap.add_argument("--config", default=str(HERE / "config.json"))
    ap.add_argument("--history-limit", type=int, default=60)
    ap.add_argument(
        "--min-confidence", type=float, default=0.25,
        help="below this, stay quiet rather than guess out loud",
    )
    args = ap.parse_args()

    config = load_config(Path(args.config))
    config["historyLimit"] = args.history_limit
    base = github_base(args.repo)

    issues = json.loads(Path(args.issues).read_text())
    scratch = Path(args.out).parent / "_issue.json"
    prepared, skipped = [], []

    for issue in issues:
        key = issue["key"]
        scratch.write_text(json.dumps(issue))
        bug, ranked = jira_source(scratch, args.repo, config)
        if bug is None:
            skipped.append((key, "no candidate file located"))
            continue

        result = analyse(args.repo, bug, config)
        if not result.suspects or result.confidence < args.min_confidence:
            skipped.append((key, "confidence %.2f below threshold" % result.confidence))
            continue

        prepared.append({
            "key": key,
            "commentId": issue.get("commentId"),
            "commentBody": render_comment(result, ranked, args.repo, base),
            "seedFile": bug.seed_file,
            "confidence": round(result.confidence, 3),
        })

    if scratch.exists():
        scratch.unlink()

    Path(args.out).write_text(json.dumps(prepared, indent=2))

    print("prepared %d comment(s); skipped %d" % (len(prepared), len(skipped)))
    for key, why in skipped:
        print("  skip %-14s %s" % (key, why))
    for p in prepared:
        print("  post %-14s seed=%s conf=%.2f"
              % (p["key"], p["seedFile"].rsplit("/", 1)[-1], p["confidence"]))
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
